Add tests (#6)
* Added testing libraries (junit 5, assertj, restassert, testcontainers, mockito).
* Removed unused method.
* Using string template.
* Refactored to make it easier to test.
* Fixed invalid sum reporting for Prometheus histograms.
* Test and fixes.
* Removed unused method.
* Updated datadog dashboard.
* Using picocli provided stdoutput (for easier testing).
* Small refactors to make things more testeable.
* Tests.
* Added awaitiity.
* Ignoring all Idea generated files.
* Added test workflow.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,10 +1,8 @@
-name: Docker Image CI
+name: Tests
 
 on:
   push:
-    branches: [ "never" ]
-  pull_request:
-    branches: [ "never" ]
+    branches: [ "*" ]
 
 jobs:
 
@@ -12,25 +10,15 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Build the Docker image
-      run: |
-        mkdir target
-        DOCKER_BUILDKIT=1 docker buildx build --output type=tar,dest=./target/docker.image.tar --platform=linux/amd64 -f docker/meshmonitor-native-image.dockerfile .
-        cd target
-        tar -xf docker.image.tar meshmonitor/meshmonitor
-        tar -xf docker.image.tar meshmonitor/meshmonitor.1
-        tar -xf docker.image.tar meshmonitor/meshmonitor.html
-        tar -xf docker.image.tar meshmonitor/meshmonitor_completion.sh
-    - name: Store an artifact
-      uses: actions/upload-artifact@v4
-      with:
-        name: meshmonitor
-        path: |
-          target/meshmonitor
-          target/meshmonitor.1
-          target/meshmonitor.html
-          target/meshmonitor.jar
-          target/meshmonitor_completion.sh
-    - name: GH Release
-      uses: softprops/action-gh-release@v0.1.15
+      - uses: actions/checkout@v4
+      - uses: actions/setup-java@v3
+        with:
+          java-version: '21'
+          distribution: 'temurin'
+      - name: Run the Maven verify phase
+        run: mvn --batch-mode --update-snapshots clean verify
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/surefire-reports/TEST-*.xml'
